version: 2.1
jobs:
    build:
        working_directory: ~/repo
        docker:
            - image: cimg/node:12.22
            - image: line/centraldogma:0.56.1
        steps:
            - checkout
            - restore_cache:
                  name: Restore Yarn Package Cache
                  keys:
                      - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: yarn install --immutable
            - save_cache:
                  name: Save Yarn Package Cache
                  key: yarn-packages-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn
            - run:
                  name: Wait for a while for starting up Central Dogma then setup test data
                  command: |
                      sleep 30
                      make setup-test-data
            - run:
                  name: Run lint
                  command: yarn lint
            - run:
                  name: Run test
                  command: yarn test
            - run:
                  name: Run build
                  command: yarn build
